[project]
name = "agentmemory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mem0ai>=0.1.112",
    "python-dotenv>=1.1.1",
]
